"""Pydantic schemas for internal service-to-service bot integration."""

from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class PublishResultCallbackRequest(BaseModel):
    """Payload sent by external publishing bots reporting job completion or failure."""

    model_config = ConfigDict(str_strip_whitespace=True)

    event_id: str = Field(..., min_length=1, max_length=64, description="Unique idempotency ID generated by the bot")
    job_id: int = Field(..., description="ID of the ContentJob that was executed")
    status: Literal["published", "failed"] = Field(..., description="Outcome of the publishing operation")
    platform_post_id: str | None = Field(default=None, max_length=255, description="Platform post/message ID if published")
    error_message: str | None = Field(default=None, max_length=2000, description="Error details if publishing failed")
    schema_version: str = Field(default="1", description="Contract schema version")


class CallbackResponse(BaseModel):
    """Response returned to external bot after processing the callback."""

    status: Literal["processed", "duplicate_ignored"]
    job_id: int
    event_id: str
    message: str
